DROP TABLE IF EXISTS invoices;

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  purchase_id BIGINT UNSIGNED NOT NULL,
  item_status ENUM('Inactive', 'Pending', 'Paid') DEFAULT 'Pending' NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  delete_at TIMESTAMP,
  PRIMARY KEY (id)
);

ALTER TABLE invoices 
ADD CONSTRAINT invoices_users
FOREIGN KEY (user_id)
REFERENCES  users(id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE invoices
ADD CONSTRAINT invoices_purchases
FOREIGN KEY (purchase_id)
REFERENCES  purchases(id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
