DROP TABLE IF EXISTS purchases;

CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  delete_at TIMESTAMP,
  PRIMARY KEY (id)
);

ALTER TABLE purchases
ADD CONSTRAINT purchases_users
FOREIGN KEY (user_id)
REFERENCES  users(id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE purchases
ADD CONSTRAINT purchases_items
FOREIGN KEY (item_id)
REFERENCES  items(id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
